### ISSUE TITLE
Still got error

### ISSUE THREAD

**Issue by InfiBatnis** [jlreymendez/greedy-merchants-ecs#2]
Same problem
I only put Svelto.ECS and Svelto.Tasks , no common (error 36), cannot find namespace
I also put the Svelto.MiniExamples /Survival/ Svelto 3.0 file ,also got (error 299), cannot find namespace
using Unity 2020.1.5f1, VS2019
![issue 3](https://user-images.githubusercontent.com/66300225/92917558-2f40c380-f461-11ea-9c2d-b45d8df5b6d6.png)

**Comment by jlreymendez** [comment]
What do you mean you only put Svelto.ECS and Svelto.Tasks? All the necessary libraries are already in the assets folder.

**Comment by jlreymendez** [comment]
Ah.. sorry, I just realized that I don't mention anywhere that i'm using git submodules for svelto. You should execute `git submodule update`

**Comment by InfiBatnis** [comment]
No, I cannot clone Svelto.ECS and Svelto.Tasks, so I download and put in

**Comment by InfiBatnis** [comment]
I try clone again, Svelto.ECS and Svelto still is empty, faild clone

**Comment by jlreymendez** [comment]
No need to clone it, git submodule takes care of this by running that command

**Comment by InfiBatnis** [comment]
how? using git bash?

**Comment by jlreymendez** [comment]
Yes, on git bash use `git submodule update` from the root of your project or outside the Svelto directory at least. That will run all the necessary clones

**Comment by InfiBatnis** [comment]
fatal: not a git repository (or any of the parent directories): .git

**Comment by InfiBatnis** [comment]
I have been researching for a long time and have not been resolved yet。
I try using  `git submodule update` but fail to update
![Screenshot (8)](https://user-images.githubusercontent.com/66300225/92932513-99646300-f477-11ea-8b8d-878dd2ffa549.png)

**Comment by InfiBatnis** [comment]
is this ssh key?
`git@github.com:jlreymendez/Svelto.ECS.git`

`git submodule update` will get the ssh key

**Comment by jlreymendez** [comment]
The proble you are having is that you don't have your ssh key configured. So quick solution would be to change the [submodules file](https://github.com/jlreymendez/greedy-merchants-ecs/blob/master/.gitmodules) to use https instead of ssh.

**Comment by InfiBatnis** [comment]
I change it, them `git submodule update`, then auto change back to ssh key

**Comment by InfiBatnis** [comment]
sorry... I change it, then git submodule update, file  the submodules still https,
git bash just get ssh key

**Comment by InfiBatnis** [comment]
sorry... I change it, then git submodule update,  the file submodules still https,
git bash just get ssh key

**Comment by jlreymendez** [comment]
That's odd! is it the same repositories giving you the error? because Svelto also uses submodules for Svelto.Common, so it could be that one is giving you an error now.

**Comment by InfiBatnis** [comment]
I think it may not be a gitmodules problem. It always shows that the namespace cannot be found. It may be a problem with visual studio or unity.
I tried https://github.com/sebas77/Svelto.MiniExamples, they all use Svelto 3.0, no problem at all.

**Comment by jlreymendez** [comment]
I will try something and see if I can remove the ssh requirement from the repo

**Comment by InfiBatnis** [comment]
also the gitmodules also have little problem

**Comment by InfiBatnis** [comment]
ok

**Comment by jlreymendez** [comment]
Ok, if you pull now, I'm certain it will work. Just use this command instead `git submodule update --init --recursive` 

Sorry, about the time it took to get this right

**Comment by InfiBatnis** [comment]
![Screenshot (9)](https://user-images.githubusercontent.com/66300225/92938022-a5075800-f47e-11ea-92a9-0446282a3981.png)

**Comment by jlreymendez** [comment]
I guess you might need to deinit first. `git submodule deinit --all -f`

**Comment by InfiBatnis** [comment]
successful! but...project
![Screenshot (11)](https://user-images.githubusercontent.com/66300225/92938937-bf8e0100-f47f-11ea-8ac0-efe751fa9fdb.png)

**Comment by InfiBatnis** [comment]
I think is unity 2020.1.2 to 2020.1.5 have problem

**Comment by jlreymendez** [comment]
Bummer, I followed the exact same steps as I indicated and it compiles correctly on my side. 😞

**Comment by jlreymendez** [comment]
Can you check the asmdef inside the `Code` directory and see if you see anything missing there?

**Comment by InfiBatnis** [comment]
have `GreedyMerchants.asmdef`

**Comment by jlreymendez** [comment]
Yes, that one. Does it have all its references correctly  set?

**Comment by InfiBatnis** [comment]
![Screenshot (12)](https://user-images.githubusercontent.com/66300225/92939497-75594f80-f480-11ea-8324-062bbee6f946.png)

**Comment by jlreymendez** [comment]
Ok hold on, I'll stop using GUIDs I think that might solve your last problem

**Comment by jlreymendez** [comment]
Try pulling now 🤞

**Comment by InfiBatnis** [comment]
ok

**Comment by InfiBatnis** [comment]
Problem solve! bro, ahahahaha

**Comment by jlreymendez** [comment]
Sorry about the time it took.

**Comment by InfiBatnis** [comment]
It's ok

**Comment by InfiBatnis** [comment]
I also learning about gitmodule today,thank a lot
